
name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Установка зависимостей
        run: npm ci
      - name: Проверка уязвимостей
        run: npm audit --production --audit-level=high || true

  build:
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - uses: actions/checkout@v3
      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Установка зависимостей
        run: npm ci
      - name: Сборка проекта
        run: npm run build
      - name: Анализ размера бандла
        run: |
          if [ -f node_modules/.bin/webpack-bundle-analyzer ]; then \
            npx webpack-bundle-analyzer dist/stats.json --mode static --no-open; \
          else \
            echo 'bundle analyzer не установлен, шаг пропущен'; \
          fi

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Логин в DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Сборка и публикация Docker-образа
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pitza:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pitza:latest
            docker stop pitza || true
            docker rm pitza || true
            docker run -d --name pitza -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/pitza:latest 